version: '3'

services:
  libreblogging:
    build: .
    restart: unless-stopped
    environment:
      - UID=1000
      - VIRTUAL_HOST=localhost
    volumes:
      - ./posts:/app/hugo-site/content/posts # Place where markdown files of your posts are located
      - ./ipfs-staging:/app/ipfs-staging     # Optional place where you can put separate data that you want to deploy on IPFS (has to be done manually using docker-compose exec)
      - ./ipfs-data:/app/ipfs-data           # Place where IPFS puts its config and data blocks
    ports:
      - 9000:9000 # Editing Web-UI
      - 9001:8000 # Blog preview
      - 4001:4001 # IPFS Swarm (Remember port forwarding!)
      - 5001:5001 # Local IPFS API
      - 8080:8080 # IPFS Gateway
